### ISSUE TITLE
Travel Agent | Travel Management & Home| Bugs

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#172]
## SUMMARY
When we deployed the Tier Status, the section was showing properly, but for some reason now the lefthand section is missing.

In addition, we need to ensure that the amounts and currency are changing based on the payout currency of the Agency.

The same thing happened to the Home, which was showing properly up until a few days ago and now shows an error message.

### ACS

- [x] Show lefthand section with details on Elite Status
- [x] Make sure the elite status threshold is changing based on the payout currency
- [x] Show the Home design with 'Book Now' and Upcoming Bookings list view

### VISUALS
Bug 1
===
**Staging**
<img width="1886" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjZPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1ff3094893a057bcfb54c4569b9bcb2a61a9da22/Screenshot%202023-12-29%20at%2010.26.36.png" alt="Screenshot 2023-12-29 at 10.26.36.png" />

**Figma**
<img width="1032" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMitPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--47273546f3735e0a27e08c6ff87f1ce803fbb21b/Screenshot%202023-12-29%20at%2010.26.52.png" alt="Screenshot 2023-12-29 at 10.26.52.png" />

Bug 2
===
**Staging**
<img width="1318" alt="Screenshot 2024-01-04 at 13 48 59" src="https://github.com/toursbylocals/wiki/assets/107880609/7eeca170-df62-4f08-8b2c-4c6f5d9ea7bb">

**Figma**
<img width="681" alt="Screenshot 2024-01-04 at 13 49 27" src="https://github.com/toursbylocals/wiki/assets/107880609/b4ddfc42-334b-46fd-9255-fd10204f17ac">

### RESOURCES
**Elite Status threshold**
USD: $7,500 USD
CAD: $9,500 CAD
EUR:  $6,500 EUR
GBP: $5,000 GBP
AUD: $10,000 AUD
JPY: $850,000 JPY

**Comment by growebux** [comment]
Admin login:
admin-agent@test.qa
Ahmad123!

User login:
user-agent@test.qa
Ahmad123!

**Comment by growebux** [comment]
The Upcoming Bookings is not working now and @miyabitanimchi will create a ticket to solve it.

Context:

PR for upcomingBookings for agents under an agency and agents.
https://github.com/toursbylocals/tblv3-api/pull/493

This code is being deleted from the codebase and we lost the functionalities of upcoming bookings under an agent and from agents under an agency. 

Changes made here:

https://github.com/toursbylocals/tblv3-api/commit/7e403d02f1cbcd87035d0dd1f6cfa2c0129a95eb

![Screenshot 2024-02-02 at 3 43 15 PM](https://github.com/toursbylocals/tblv3-api/assets/70495348/fcbefd9f-9868-4fd2-8450-d4f2a9e9f1d4)

I communicated with @miyabitanimchi about it she is taking care of restoring the feature.

I will move my ticket to review and when the problem is fixed the users will be able to see the upcoming bookings https://github.com/toursbylocals/wiki/issues/172

_Originally posted by @growebux in https://github.com/toursbylocals/tblv3-api/issues/493#issuecomment-1924912242_

**Comment by growebux** [comment]
@Mica-pfl @sebas-led @kateinvan @laskokonopa @ecurtosi99 

Could you validate?

**Comment by sebas-led** [comment]
@growebux 
- Any idea why the image is not showing?

<img width="1029" alt="Screenshot 2024-02-05 at 09 37 42" src="https://github.com/toursbylocals/wiki/assets/107880609/4d19b610-e6c8-431f-b0ce-54fa6ff52508">

- Same issue as with rest password. URL is leading to a 404 due to undefined when clicking on `wishlist`: https://tblv3-kitchen-staging-c94ff87374cd.herokuapp.com/undefinedwishlist

- There is an ACS for `Make sure the elite status threshold is changing based on the payout currency`. Admin user shared to QA has currency in CAD but threshold is from USD (7,500). For CAD, it should be 9,500 as per the info under `RESOURCES` in this ticket

<img width="971" alt="Screenshot 2024-02-05 at 09 40 08" src="https://github.com/toursbylocals/wiki/assets/107880609/839bdf1b-89c1-4a4c-9178-21d38a9cc494">

- Just to confirm, but if user and admin are from the same agency, the amounts showing under Elite Status should be the same as it's for the Agency and not per Agent. If the users shared are not from the same Agency, then you can disregard this comment. Could you confirm?

User Agent
<img width="981" alt="Screenshot 2024-02-05 at 09 44 11" src="https://github.com/toursbylocals/wiki/assets/107880609/280ae5c3-eaa6-4978-981a-7c44ad11dfa5">

Admin Agent
<img width="953" alt="Screenshot 2024-02-05 at 09 45 00" src="https://github.com/toursbylocals/wiki/assets/107880609/27b2577f-2cca-457b-8450-d1f1b5d6cfb7">

**Comment by kateinvan** [comment]
same as Seba's comments, but other than that LGTM

**Comment by growebux** [comment]
@sebas-led about the image I have to check with @nk18chi on Heroku, on our local the image works correctly.

**Comment by growebux** [comment]
@sebas-led 

Total Sales Calculation for an Agency

Identify Agents: Find all agents associated with the agency.

Date Range: Determine the date range for the calculation, typically for the previous year.
Aggregate Sales Data:
Filter bookings made by these agents within the specified date range.
For each booking, calculate the total price, which includes the base tour price, the number of adults attending, and any additional costs from add-ons.
Sum up these total prices for each currency.
Convert Currency: Convert the total sales from various currencies into the agency's preferred currency, using current exchange rates.
Total Sales: The sum of these converted amounts is the agency's total sales for that period.
Total Sales Calculation for an Agent

Specify Agent: Focus on bookings made by a specific agent.
Date Range: Same as for the agency, typically covering the previous year.
Aggregate Sales Data:
Similar to the agency calculation, but only for bookings made by the specified agent.
Calculate the total price for each booking.
Sum up these totals for each currency.
Convert Currency: Convert these totals into the agency's preferred currency using current exchange rates.
Total Sales: The sum of the converted amounts gives the total sales made by the agent.
Currency Conversion

Conversion Process: For each currency in which sales were made, convert the total sales amount into the agency's preferred currency.
Sum Up: Add all these converted amounts to get the final total sales in the preferred currency.

**Comment by growebux** [comment]
@sebas-led Here's a summary of the implementation aligned with the ACs from [Issue #996](https://github.com/toursbylocals/tblv3/issues/996) and [API Pull Request #523](https://github.com/toursbylocals/tblv3-api/pull/523):

### Backend Implementation:

**Total Sales Calculation for an Agency:**
- **Identify Agents**: All agents associated with the agency.
- **Date Range**: Sales are calculated typically covering the previous year.
- **Aggregate Sales Data**:
   - Bookings by these agents within the specified date range are filtered.
   - The total price for each booking includes base tour price, number of adults, and add-on costs.
   - Total prices across all currencies are summed.
   - Sales are converted into the agency’s preferred currency using current exchange rates.

**Total Sales Calculation for an Agent:**
- **Agent Specificity**: Calculations focus on bookings made by a specified agent.
- **Consistency with Agency Calculation**: Similar methodology but applied to individual agent's bookings.

**Currency Conversion:**
- Sales in various currencies are converted into the agency's preferred currency.

### Frontend Implementation:

- **Currency Display**: Values are displayed in the agency’s preferred currency.
- **Fixed Sales Cap**: A maximum threshold of 7,500 is applied for Elite Status visualization.

### New Requirements Not Initially Specified:

- **Dynamic Elite Status Threshold**: This point seems to focus more on displaying the threshold in the agency's preferred currency, including the currency code, rather than specifying that the threshold value itself should be different for different currencies. The level of detail and specificity regarding dynamic thresholds is not clearly outlined in the original acs.)

- **Sales Cap Relative to Elite Status**: Implementing a maximum sales cap in relation to the Elite Status threshold was also not initially specified.

### Action :

- **Dynamic Threshold Adjustment**: Implement logic to dynamically map each currency to its respective threshold, applying this when calculating and displaying sales necessary to achieve Elite Status.

I have a question for you after reading this. We can have a call soon.

**Comment by growebux** [comment]
@sebas-led 

The changes will be deployed here:

https://github.com/toursbylocals/kitchen/pull/238

**Comment by growebux** [comment]
The changes are applied here:

@Mica-pfl @sebas-led @kateinvan @laskokonopa @ecurtosi99

Could you validate?


Link: https://tblv3-kitchen-staging-c94ff87374cd.herokuapp.com/agent/travel-management

Admin login:
[admin-agent@test.qa](mailto:admin-agent@test.qa)
Ahmad123!

User login:
[user-agent@test.qa](mailto:user-agent@test.qa)
Ahmad123!

**Comment by kateinvan** [comment]
LGTM

**Comment by ecurtosi99** [comment]
LGTM
