### ISSUE TITLE
Adyen Integration | Refunds

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#92]
**Background**
We capture and split the funds on Adyen after Guide Accepts the booking. If a booking status is changed to canceled, we need to process the refunds to the Customer's payment method on Adyen following the business rules:

Tour Date is more than 15 days:
- No Policy: Refund Tour Price (including any taxes), following the same split as on capture
- Policy purchased: Refund Tour Price (including any taxes), following the same split as on capture + Create a Promo Code for the value of the enhanced cancellation policy

Tour Date is less than 15 days and Enhanced Cancellation Policy was purchased:
- No Policy: No refund
- Policy purchased: Refund Tour Price (including any taxes), following the same split as on capture

**ACS**

- [ ] Create automatic refund on Adyen when booking status is changed to `CANCELED` and Tour Date is more than 15 days
- [ ] Create automatic refund on Adyen when booking status is changed to `CANCELED` and Tour Date is less than 15 days and Enhanced Cancellation Policy was purchased

**Comment by nk18chi** [comment]
## Q&A

- Do you think we need to create a flowchart for refunds in Excalidraw?
Probably not, because the refund process is simple in Adyen. We just need to call a refund API and receive a webhook event indicating success or failure.
[Adyen Refund Documentation](https://docs.adyen.com/online-payments/refund)

- Does the refund require approval from TBL?
Yes, the TBL staff will manually change the status to 'cancelled'. When a customer requests a refund in the marketplace, the status changes to "cancelInProgress," and TBL will change it to "cancelled" after verifying it.

**Comment by growebux** [comment]
Q&A

- How does the system identify and confirm the original transaction on Adyen for which the refund needs to be issued?

- Considering the manual intervention by TBL staff in the process, is there a need to build in a notification mechanism for them when a booking is marked as "cancelInProgress"?

- Are there any particular error codes or exceptions from Adyen's refund API that we need to be prepared for?

**Comment by nk18chi** [comment]
### The status of this ticket
The refund process is dependent on how the money is split, and the promo code also has an impact on this ticket. The ticket for splitting the money is currently blocked due to issues with Adyen and the booking structure. It is currently in a waiting status.

Payment Processor Integration | Webhook for Pay In | Splits
https://github.com/toursbylocals/tblv3-api/issues/271

### Assignee
Marty initially started working on this task, but he would be transitioning back to the frontend as the new branding UI was getting ready. I will be taking over responsibility for this task.
